import {
  BuyerFeedProduct,
  MarketItem,
  UserOrder,
  Transaction,
  DriverData,
  ProductCategoryItem,
} from '../types/buyer';

export const TAMIL_NADU_CITIES = [
  'Chennai',
  'Coimbatore',
  'Madurai',
  'Tiruchirappalli',
  'Salem',
  'Tirunelveli',
  'Erode',
  'Vellore',
  'Thanjavur',
  'Dindigul',
];

export const BUYER_CATEGORIES: ProductCategoryItem[] = [
  {
    id: 'cat-veg',
    name: 'Vegetables',
    count: '42+ Items',
    categoryKey: 'vegetables',
    image: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=300&auto=format&fit=crop&q=80',
  },
  {
    id: 'cat-fruits',
    name: 'Fruits',
    count: '35+ Items',
    categoryKey: 'fruits',
    image: 'https://images.unsplash.com/photo-1619566636858-adf3ef46400b?w=300&auto=format&fit=crop&q=80',
  },
  {
    id: 'cat-flowers',
    name: 'Flowers',
    count: '18+ Items',
    categoryKey: 'flowers',
    image: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?w=300&auto=format&fit=crop&q=80',
  },
  {
    id: 'cat-grains',
    name: 'Grains & Cereals',
    count: '26+ Items',
    categoryKey: 'grains',
    image: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=300&auto=format&fit=crop&q=80',
  },
  {
    id: 'cat-dairy',
    name: 'Dairy & Milk',
    count: '15+ Items',
    categoryKey: 'dairy',
    image: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?w=300&auto=format&fit=crop&q=80',
  },
  {
    id: 'cat-eggs',
    name: 'Farm Fresh Eggs',
    count: '8+ Items',
    categoryKey: 'eggs',
    image: 'https://images.unsplash.com/photo-1582722872445-44dc5f7e3c8f?w=300&auto=format&fit=crop&q=80',
  },
  {
    id: 'cat-organic',
    name: 'Organic Products',
    count: '50+ Items',
    categoryKey: 'organic',
    image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=300&auto=format&fit=crop&q=80',
  },
  {
    id: 'cat-all',
    name: 'Shop All',
    count: '350+ Items',
    categoryKey: 'all',
    image: 'https://images.unsplash.com/photo-1488459716781-31db52582fe9?w=300&auto=format&fit=crop&q=80',
  },
];

export const BUYER_MARKET_DATA: MarketItem[] = [
  { name: 'Tomato', price: '₹35/kg', trend: 'up', predicted: '₹38/kg' },
  { name: 'Onion', price: '₹28/kg', trend: 'down', predicted: '₹25/kg' },
  { name: 'Potato', price: '₹22/kg', trend: 'up', predicted: '₹24/kg' },
  { name: 'Carrot', price: '₹40/kg', trend: 'stable', predicted: '₹40/kg' },
  { name: 'Brinjal', price: '₹30/kg', trend: 'up', predicted: '₹33/kg' },
  { name: 'Cabbage', price: '₹25/kg', trend: 'down', predicted: '₹22/kg' },
  { name: 'Cauliflower', price: '₹32/kg', trend: 'up', predicted: '₹36/kg' },
  { name: 'Green Chilli', price: '₹55/kg', trend: 'up', predicted: '₹60/kg' },
  { name: 'Salem Mango', price: '₹85/kg', trend: 'up', predicted: '₹95/kg' },
  { name: 'Madurai Jasmine', price: '₹240/kg', trend: 'up', predicted: '₹260/kg' },
];

export const BUYER_FEED_PRODUCTS: BuyerFeedProduct[] = [
  {
    id: 1,
    productName: 'Fresh Organic Tomatoes',
    grade: 'A',
    category: 'vegetables',
    productImg: 'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=800&auto=format&fit=crop&q=80',
    farmerName: 'Prakash Kumar',
    location: 'Coimbatore, TN',
    rate: 35,
    originalPrice: 45,
    rating: 4.8,
    description: 'Fresh, 100% pesticide-free red tomatoes harvested this morning directly from organic farm fields in Pollachi. Firm texture, high lycopene, and naturally sweet.',
    coords: { lat: 11.0168, lng: 76.9558 },
    quantityAvailable: '250 kg',
    unit: 'kg',
    badge: 'Harvested 4h ago',
    harvestTime: '6:30 AM Today',
  },
  {
    id: 2,
    productName: 'Country Red Onions',
    grade: 'B',
    category: 'vegetables',
    productImg: 'https://images.unsplash.com/photo-1618512496248-a07fe83aa8cb?w=800&auto=format&fit=crop&q=80',
    farmerName: 'Suresh Farms',
    location: 'Pollachi, TN',
    rate: 28,
    originalPrice: 34,
    rating: 4.7,
    description: 'Pungent, flavorful farm-cured red country onions. Exceptional shelf life and robust aroma ideal for everyday South Indian cooking and wholesale stock.',
    coords: { lat: 10.6621, lng: 77.0118 },
    quantityAvailable: '500 kg',
    unit: 'kg',
    badge: 'Direct Cured',
    harvestTime: 'Yesterday',
  },
  {
    id: 3,
    productName: 'Hill Fresh Ooty Carrots',
    grade: 'A',
    category: 'vegetables',
    productImg: 'https://images.unsplash.com/photo-1598170845058-32b9d6a5da37?w=800&auto=format&fit=crop&q=80',
    farmerName: 'Organic Greens Nilgiris',
    location: 'Ooty Nilgiris, TN',
    rate: 40,
    originalPrice: 52,
    rating: 4.9,
    description: 'Crisp, bright orange carrots grown in cool mountain soil at 2,200m altitude. Highly sweet with tender core, perfect for juice, salads, and curries.',
    coords: { lat: 11.4102, lng: 76.695 },
    quantityAvailable: '180 kg',
    unit: 'kg',
    badge: 'Nilgiris GI Tag',
    harvestTime: '5:00 AM Today',
  },
  {
    id: 4,
    productName: 'Salem Alphonso Mangoes',
    grade: 'A',
    category: 'fruits',
    productImg: 'https://images.unsplash.com/photo-1553279768-865429fa0078?w=800&auto=format&fit=crop&q=80',
    farmerName: 'Selvam Orchard',
    location: 'Salem, TN',
    rate: 85,
    originalPrice: 110,
    rating: 4.9,
    description: 'Tree-ripened, aromatic Salem Alphonso mangoes with rich saffron pulp and zero artificial carbide ripening. Authentic naturally ripened sweet taste.',
    coords: { lat: 11.6643, lng: 78.146 },
    quantityAvailable: '350 kg',
    unit: 'kg',
    badge: 'Naturally Ripened',
    harvestTime: 'Yesterday',
  },
  {
    id: 5,
    productName: 'Madurai Jasmine (Gundu Malli)',
    grade: 'A',
    category: 'flowers',
    productImg: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?w=800&auto=format&fit=crop&q=80',
    farmerName: 'Meenakshi Floral Farm',
    location: 'Madurai, TN',
    rate: 240,
    originalPrice: 280,
    rating: 5.0,
    description: 'Authentic GI-tagged Madurai Malli buds, handpicked before dawn with intense natural fragrance. Plump buds with long-lasting freshness.',
    coords: { lat: 9.9252, lng: 78.1198 },
    quantityAvailable: '60 kg',
    unit: 'kg',
    badge: 'GI Tagged',
    harvestTime: '4:30 AM Today',
  },
  {
    id: 6,
    productName: 'Thanjavur Ponni Raw Rice',
    grade: 'A',
    category: 'grains',
    productImg: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=800&auto=format&fit=crop&q=80',
    farmerName: 'Cauvery Delta Farmers',
    location: 'Thanjavur, TN',
    rate: 58,
    originalPrice: 70,
    rating: 4.8,
    description: 'Aged 1-year authentic Ponni raw rice irrigated by Cauvery river waters. Slender grains, non-sticky texture, and traditional South Indian rice flavor.',
    coords: { lat: 10.787, lng: 79.1378 },
    quantityAvailable: '1200 kg',
    unit: 'kg',
    badge: 'Delta Harvest',
    harvestTime: 'Season Batch',
  },
  {
    id: 7,
    productName: 'Farm Fresh Country Eggs (Nattu Kozhi)',
    grade: 'A',
    category: 'eggs',
    productImg: 'https://images.unsplash.com/photo-1582722872445-44dc5f7e3c8f?w=800&auto=format&fit=crop&q=80',
    farmerName: 'Namakkal Free-Range Farm',
    location: 'Namakkal, TN',
    rate: 9,
    originalPrice: 12,
    rating: 4.9,
    description: 'Pasture-raised country hen eggs with deep golden yolks. High in Omega-3 and natural protein without antibiotics or hormonal feeds.',
    coords: { lat: 11.2189, lng: 78.1674 },
    quantityAvailable: '800 pcs',
    unit: 'piece',
    badge: 'Free-Range',
    harvestTime: 'Today Morning',
  },
  {
    id: 8,
    productName: 'Pure Gir Cow A2 Milk & Curd',
    grade: 'A',
    category: 'dairy',
    productImg: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?w=800&auto=format&fit=crop&q=80',
    farmerName: 'Gomatha Dairy Collective',
    location: 'Erode, TN',
    rate: 65,
    originalPrice: 75,
    rating: 4.9,
    description: '100% unadulterated grass-fed native cow A2 raw milk chilled immediately after morning milking. Rich in wholesome nutrients and natural taste.',
    coords: { lat: 11.341, lng: 77.7172 },
    quantityAvailable: '150 L',
    unit: 'L',
    badge: 'Cold-Chained',
    harvestTime: '5:30 AM Today',
  },
  {
    id: 9,
    productName: 'Tender Purple Brinjals',
    grade: 'A',
    category: 'vegetables',
    productImg: 'https://images.unsplash.com/photo-1628773822503-930a84260387?w=800&auto=format&fit=crop&q=80',
    farmerName: 'Kavitha Devi',
    location: 'Madurai, TN',
    rate: 30,
    originalPrice: 38,
    rating: 4.6,
    description: 'Glossy, seedless green-purple striped brinjals grown without chemical insecticides. Melts smoothly in gravy, chutney, and sambar.',
    coords: { lat: 9.9252, lng: 78.1198 },
    quantityAvailable: '120 kg',
    unit: 'kg',
    badge: 'No Chemicals',
    harvestTime: 'Today Morning',
  },
  {
    id: 10,
    productName: 'Crisp Green Cabbage',
    grade: 'B',
    category: 'vegetables',
    productImg: 'https://images.unsplash.com/photo-1594282486552-05b4d80fbb9f?w=800&auto=format&fit=crop&q=80',
    farmerName: 'Kodaikanal Naturals',
    location: 'Kodaikanal, TN',
    rate: 25,
    originalPrice: 32,
    rating: 4.7,
    description: 'Tightly packed, heavy cabbage heads rich in vitamins C and K. Crunchy texture and fresh aroma straight from the cool hill harvest.',
    coords: { lat: 10.2381, lng: 77.4892 },
    quantityAvailable: '320 kg',
    unit: 'kg',
    badge: 'Hill Grown',
    harvestTime: 'Yesterday',
  },
  {
    id: 11,
    productName: 'Dindigul Traditional Garlic',
    grade: 'A',
    category: 'organic',
    productImg: 'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?w=800&auto=format&fit=crop&q=80',
    farmerName: 'Dindigul Agri Society',
    location: 'Dindigul, TN',
    rate: 180,
    originalPrice: 220,
    rating: 4.8,
    description: 'Potent, high-allicin small clove country garlic. Known for therapeutic properties and pungent flavor in medicinal rasam and south Indian dishes.',
    coords: { lat: 10.3673, lng: 77.9803 },
    quantityAvailable: '200 kg',
    unit: 'kg',
    badge: 'High Medicinal',
    harvestTime: 'Cured Batch',
  },
  {
    id: 12,
    productName: 'Fresh Kodaikanal Strawberries',
    grade: 'A',
    category: 'fruits',
    productImg: 'https://images.unsplash.com/photo-1464965911861-746a04b4bca6?w=800&auto=format&fit=crop&q=80',
    farmerName: 'Misty Valley Berries',
    location: 'Kodaikanal, TN',
    rate: 160,
    originalPrice: 200,
    rating: 4.9,
    description: 'Succulent ruby-red hill strawberries cultivated in organic mulch beds. Naturally sweet-tart balance packed in breathable pulp boxes.',
    coords: { lat: 10.2381, lng: 77.4892 },
    quantityAvailable: '90 boxes',
    unit: 'box',
    badge: 'Cold Chilled',
    harvestTime: 'Today Morning',
  },
];

export const BUYER_USER_ORDERS: UserOrder[] = [
  {
    id: 'ORD-8921',
    itemKey: 'gradeATomatoes',
    productName: 'Fresh Organic Tomatoes',
    farmerName: 'Prakash Kumar (Pollachi)',
    quantity: '50 kg',
    productImg: 'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=800&auto=format&fit=crop&q=80',
    date: '2026-09-18',
    amount: '₹1,750',
    statusKey: 'ongoing',
  },
  {
    id: 'ORD-8814',
    itemKey: 'freshCarrots',
    productName: 'Hill Fresh Ooty Carrots',
    farmerName: 'Organic Greens Nilgiris',
    quantity: '50 kg',
    productImg: 'https://images.unsplash.com/photo-1598170845058-32b9d6a5da37?w=800&auto=format&fit=crop&q=80',
    date: '2026-09-15',
    amount: '₹2,000',
    statusKey: 'delivered',
  },
  {
    id: 'ORD-8702',
    itemKey: 'countryOnions',
    productName: 'Country Red Onions',
    farmerName: 'Suresh Farms',
    quantity: '50 kg',
    productImg: 'https://images.unsplash.com/photo-1618512496248-a07fe83aa8cb?w=800&auto=format&fit=crop&q=80',
    date: '2026-09-10',
    amount: '₹1,400',
    statusKey: 'delivered',
  },
  {
    id: 'ORD-8610',
    itemKey: 'salemMangoes',
    productName: 'Salem Alphonso Mangoes',
    farmerName: 'Selvam Orchard',
    quantity: '30 kg',
    productImg: 'https://images.unsplash.com/photo-1553279768-865429fa0078?w=800&auto=format&fit=crop&q=80',
    date: '2026-09-04',
    amount: '₹2,550',
    statusKey: 'delivered',
  },
];

export const BUYER_TRANSACTIONS: Transaction[] = [
  {
    id: 'TXN-94021',
    itemKey: 'gradeATomatoes',
    itemName: 'Fresh Organic Tomatoes (50kg)',
    date: '18 Sep 2026, 08:30 AM',
    amount: '₹1,750',
    typeKey: 'debit',
    status: 'completed',
    paymentMethod: 'UPI • Google Pay (Axis Bank)',
    referenceId: 'UPI-984210984129',
    category: 'produce',
    farmerName: 'Prakash Kumar (Pollachi)',
    breakdown: {
      produceTotal: 1750,
      farmerDirectShare: 1610,
      logisticsFee: 100,
      platformFee: 40,
      gstTax: 0,
    },
  },
  {
    id: 'TXN-93810',
    itemKey: 'walletTopUp',
    itemName: 'Uzhavan Direct Wallet Recharge',
    date: '17 Sep 2026, 04:15 PM',
    amount: '₹5,000',
    typeKey: 'credit',
    status: 'completed',
    paymentMethod: 'Net Banking • HDFC Bank',
    referenceId: 'HDFC-8819203194',
    category: 'wallet',
    breakdown: {
      produceTotal: 5000,
      farmerDirectShare: 0,
      logisticsFee: 0,
      platformFee: 0,
      gstTax: 0,
    },
  },
  {
    id: 'TXN-93112',
    itemKey: 'freshCarrots',
    itemName: 'Hill Fresh Ooty Carrots (50kg)',
    date: '15 Sep 2026, 09:20 AM',
    amount: '₹2,000',
    typeKey: 'debit',
    status: 'completed',
    paymentMethod: 'UPI • PhonePe (SBI)',
    referenceId: 'UPI-771290348102',
    category: 'produce',
    farmerName: 'Organic Greens Nilgiris',
    breakdown: {
      produceTotal: 2000,
      farmerDirectShare: 1840,
      logisticsFee: 120,
      platformFee: 40,
      gstTax: 0,
    },
  },
  {
    id: 'TXN-92841',
    itemKey: 'cashbackReward',
    itemName: 'Direct Farmer Support Cashback Reward',
    date: '12 Sep 2026, 11:45 AM',
    amount: '₹250',
    typeKey: 'credit',
    status: 'completed',
    paymentMethod: 'Uzhavan Loyalty Credit',
    referenceId: 'REWARD-29184',
    category: 'reward',
  },
  {
    id: 'TXN-92405',
    itemKey: 'countryOnions',
    itemName: 'Country Red Onions (50kg)',
    date: '10 Sep 2026, 07:50 AM',
    amount: '₹1,400',
    typeKey: 'debit',
    status: 'completed',
    paymentMethod: 'UPI • Paytm Payments',
    referenceId: 'UPI-4921058201',
    category: 'produce',
    farmerName: 'Suresh Farms (Pollachi)',
    breakdown: {
      produceTotal: 1400,
      farmerDirectShare: 1290,
      logisticsFee: 80,
      platformFee: 30,
      gstTax: 0,
    },
  },
  {
    id: 'TXN-91902',
    itemKey: 'salemMangoes',
    itemName: 'Salem Alphonso Mangoes (30kg crate)',
    date: '04 Sep 2026, 02:10 PM',
    amount: '₹2,550',
    typeKey: 'debit',
    status: 'completed',
    paymentMethod: 'UPI • Google Pay',
    referenceId: 'UPI-3910582019',
    category: 'produce',
    farmerName: 'Selvam Orchard (Salem)',
    breakdown: {
      produceTotal: 2550,
      farmerDirectShare: 2350,
      logisticsFee: 150,
      platformFee: 50,
      gstTax: 0,
    },
  },
];

export const BUYER_CART_INITIAL = [
  {
    id: 1,
    productName: 'Fresh Organic Tomatoes',
    farmerName: 'Prakash Kumar',
    rate: 35,
    quantity: 10,
    productImg: 'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=800&auto=format&fit=crop&q=80',
    unit: 'kg',
  },
  {
    id: 3,
    productName: 'Hill Fresh Ooty Carrots',
    farmerName: 'Organic Greens Nilgiris',
    rate: 40,
    quantity: 5,
    productImg: 'https://images.unsplash.com/photo-1598170845058-32b9d6a5da37?w=800&auto=format&fit=crop&q=80',
    unit: 'kg',
  },
  {
    id: 2,
    productName: 'Country Red Onions',
    farmerName: 'Suresh Farms',
    rate: 28,
    quantity: 10,
    productImg: 'https://images.unsplash.com/photo-1618512496248-a07fe83aa8cb?w=800&auto=format&fit=crop&q=80',
    unit: 'kg',
  },
];

export const BUYER_WISHLIST_INITIAL = [
  {
    id: 4,
    productName: 'Salem Alphonso Mangoes',
    farmerName: 'Selvam Orchard (Salem)',
    rate: 85,
    productImg: 'https://images.unsplash.com/photo-1553279768-865429fa0078?w=800&auto=format&fit=crop&q=80',
  },
  {
    id: 5,
    productName: 'Madurai Jasmine (Gundu Malli)',
    farmerName: 'Meenakshi Floral Farm (Madurai)',
    rate: 240,
    productImg: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?w=800&auto=format&fit=crop&q=80',
  },
];

export const BUYER_DRIVER_DATA: DriverData = {
  name: 'Rajesh Kumar',
  vehicleModel: 'Tata Ace Gold Super',
  vehicleNumber: 'TN 38 AZ 1234',
  pictureUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&auto=format&fit=crop&q=80',
  phone: '+91 98421 78901',
};
